settings:
  application:
    domain: localhost:9110
    host: 0.0.0.0
    ishttps: false
    mode: dev
    name: testApp
    port: "9110"
    readtimeout: 1
    writertimeout: 2
  database:
    dbtype: mysql
    host: 127.0.0.1
    name: goadmindb
    password: root
    port: 3306
    username: root
  jwt:
    secret: go-admin
    timeout: 3600
  log:
    dir: temp/logs
    operdb: false
  ssl:
    key: keystring
    pem: temp/pem.pem
